### ISSUE TITLE
Issue with IVY - lwjgl

### ISSUE THREAD

**Issue by djeang** [jerkar/jeka#103]
I tried to understand the confusing lwjgl-dependency errors. I think the problem is with IVY. I wrote a minimal project to test it. You need to adjust the .classpath file to make it work.

Examine and run IvyApiExperiments.java

The example downloads all dependencies using the ivy-2.0.xml for organisation="io.playn" module="playn-java-lwjgl" revision="2.0"

It's all very confusing. It seems to work to download all the dependencies (jars) correctly, except for lwjgl. In Step2 (see code comments) only the native jars for macos are downloaded to the ivy-cache. For example:

~/.ivy2/cache/org.lwjgl/lwjgl/ jars/lwjgl-3.1.2-natives-macos .jar

In Step3 I tell Ivy to download (retrieve) the dependencies to a local folder. It works great for all dependencies but those of lwjgl. It downloads jars like 
ivy-experiments/retrieved/org. lwjgl/lwjgl/jar/lwjgl-3.1.2.ja r

...but when you open the jar, you notice that it doesn't contain the expected .class files but liblwjgl.dylib. What is going on here?

Here is the correct jar for comparison: http://central.mav en.org/maven2/org/lwjgl/lwjgl/ 3.1.2/lwjgl-3.1.2.jar

The problem seems to be with Ivy and not for example in the Maven repo. I can retrieve all dependencies of organisation="io.playn" module="playn-java-lwjgl" revision="2.0" with GRADLE without problems.

I think the way to go is to understand and fix this minimal ivy example and then apply the fix to Jerkar. Can you look at the example?

**Comment by djeang** [comment]
Issue is coming from Ivy 2.4.0. Ivy 2.5.0-rc1 fixes it but introduces new blocking bug https://issues.apache.org/jira/projects/IVY/issues/IVY-1586?filter=allopenissues

**Comment by NekoCaffeine** [comment]
I have encountered this problem now, how is the progress?

**Comment by djeang** [comment]
Waiting for Ivy 2.5.0 that should fix it.
I think it is a question of weeks.

**Comment by NekoCaffeine** [comment]
> Waiting for Ivy 2.5.0 that should fix it.
> I think it is a question of weeks.

https://mvnrepository.com/artifact/org.apache.ivy/ivy/2.5.0 Do you mean this?

**Comment by NekoCaffeine** [comment]
When I do this, it seems that everything works fine?
```java
    private JkDependencySet dependencies() {
        return JkDependencySet.of()
                .andFiles(getBaseTree().andMatching(true, "libs/*.jar").getFiles())
                .and("org.ow2.asm:asm:+")
                .and("org.ow2.asm:asm-tree:+")
                .and("org.ow2.asm:asm-commons:+")
                .and("org.ow2.asm:asm-util:+")
                .and("net.java.dev.jna:jna:+")
                .and("net.java.dev.jna:jna-platform:+")
                .and("org.checkerframework:checker-qual:+")
                .and("org.jetbrains:annotations:+", PROVIDED)
                .and("org.lwjgl:lwjgl:" + lwjglVersion)
                .and("org.lwjgl:lwjgl-assimp:" + lwjglVersion)
                .and("org.lwjgl:lwjgl-bgfx:" + lwjglVersion)
                .and("org.lwjgl:lwjgl-glfw:" + lwjglVersion)
                .and("org.lwjgl:lwjgl-lz4:" + lwjglVersion)
                .and("org.lwjgl:lwjgl-openal:" + lwjglVersion)
                .and("org.lwjgl:lwjgl-opencl:" + lwjglVersion)
                .and("org.lwjgl:lwjgl-opengl:" + lwjglVersion)
                .and("org.lwjgl:lwjgl-opus:" + lwjglVersion)
                .and("org.lwjgl:lwjgl-par:" + lwjglVersion)
                .and("org.lwjgl:lwjgl-stb:" + lwjglVersion)
                .and("org.lwjgl:lwjgl-vulkan:" + lwjglVersion)
                .and("org.lwjgl:lwjgl-xxhash:" + lwjglVersion)
                .and(JkModuleDependency.of("org.lwjgl:lwjgl:" + lwjglVersion).withClassifier(lwjglNatives))
                .and(JkModuleDependency.of("org.lwjgl:lwjgl-assimp:" + lwjglVersion).withClassifier(lwjglNatives))
                .and(JkModuleDependency.of("org.lwjgl:lwjgl-bgfx:" + lwjglVersion).withClassifier(lwjglNatives))
                .and(JkModuleDependency.of("org.lwjgl:lwjgl-glfw:" + lwjglVersion).withClassifier(lwjglNatives))
                .and(JkModuleDependency.of("org.lwjgl:lwjgl-lz4:" + lwjglVersion).withClassifier(lwjglNatives))
                .and(JkModuleDependency.of("org.lwjgl:lwjgl-openal:" + lwjglVersion).withClassifier(lwjglNatives))
                .and(JkModuleDependency.of("org.lwjgl:lwjgl-opengl:" + lwjglVersion).withClassifier(lwjglNatives))
                .and(JkModuleDependency.of("org.lwjgl:lwjgl-opus:" + lwjglVersion).withClassifier(lwjglNatives))
                .and(JkModuleDependency.of("org.lwjgl:lwjgl-par:" + lwjglVersion).withClassifier(lwjglNatives))
                .and(JkModuleDependency.of("org.lwjgl:lwjgl-stb:" + lwjglVersion).withClassifier(lwjglNatives))
                .and(JkModuleDependency.of("org.lwjgl:lwjgl-xxhash:" + lwjglVersion).withClassifier(lwjglNatives))
                .and("org.joml:joml:" + jomlVersion)
                .and("com.code-disaster.steamworks4j:steamworks4j:" + steamworks4jVersion)
                .and("com.code-disaster.steamworks4j:steamworks4j-server:" + steamworks4jServerVersion)
                .andFiles(getBaseTree().andMatching(true, "plugins/*.jar").getFiles(), PROVIDED);
    }
```
![image](https://user-images.githubusercontent.com/10548315/68974325-6fc4b600-082b-11ea-9d3e-1aa193379984.png)

**Comment by djeang** [comment]
> https://mvnrepository.com/artifact/org.apache.ivy/ivy/2.5.0 Do you mean this?

Right, it has been released recently. I will integrate it in the next days :-)
