### ISSUE TITLE
Is there a roadmap?

### ISSUE THREAD

**Issue by Sandared** [jerkar/jeka#111]
Hi,

first of all, thanks for the great work you put into this build tool.

My question is: Is there any roadmap regarding version 0.7? And is the documentation on the website obsolete with this release or does it already describe the API and stuff as it is intended to be with version 0.7?

I'd like to use Jerkar for our OSGi projects in conjunction with bnd and before I start, I wanted to know if I should wait for the official relese of the new version or not.

Kind regards,
Thomas

**Comment by djeang** [comment]
Hi Thomas,

Thanks to take attention on this project.

Jerkar is under deep reworking in order to leverage of latest JKD7 & 8 features (NIO & lambda). The trunk version is usable  and brings great improvements but the gap between 0.6 and next release is so big that I forseen to jump to 0.8 and maybe to change project name (I was told 'Jerkar' sounds weird for native english speakers).  Also I consider trunk is still experimental and current API is likely to change somehow. 

Therefore official documentation from site does not match anymore. Best documentation available is the project 'org.jerkar.sample' on this repository. 

Anyway, I would be happy if you try Jerkar on your project and provide me some feedback. I am confortable with implementing features for early adopters. 

Regards

**Comment by Sandared** [comment]
Thanks for the information. Any guess on when version 0.8 will be ready?

It would be great if you find some spare time to enable something like the [bnd-gradle-plugin](https://github.com/bndtools/bnd/blob/master/biz.aQute.bnd.gradle/README.md#gradle-plugin-for-workspace-builds) workspace builds for jerkar. This would help me to finally get rid of gradle in my OSGi projects ;)

Kind regards,
Thomas

**Comment by djeang** [comment]
I hope 0.8 release for 2018 Q4, 
Almost all feaures are here but it needs API polish and more testing.

Sure, I'll have a look at bnd/osgi for Jerkar soon.

Kind Regards

**Comment by Sandared** [comment]
Wow! Thanks a lot :)

**Comment by Sandared** [comment]
I had a look into Jerkar and bnd/osgi. So if you still plan to create a plugin for bnd, then this might be a starting point :)

The following is a working workspace build as described by bnd.
A bnd workspace always looks like this:

\
- cnf
  - ext
    - myplugins.bnd
  - build.bnd
- project1
- project2

If you sturcture your workspace like this, then you can add the following build file to cnf/build/def , which then builds all the projects in your workspace (it's written in Xtend, but should be understandable):

```
package cnf

import aQute.bnd.build.Workspace
import org.jerkar.api.file.JkPathTree
import org.jerkar.api.java.JkJavaCompileSpec
import org.jerkar.api.java.JkJavaCompiler
import org.jerkar.tool.JkBuild
import org.jerkar.tool.JkInit

import static org.jerkar.api.system.JkLog.*

class BndWorkspaceBuild extends JkBuild{
	
	val workspaceLoc = baseDir.parent
	
	override doDefault() {
		var Workspace workspace
		try {
			startTask('Creating bnd workspace')
			workspace = Workspace.getWorkspace(workspaceLoc.toFile)
			endTask('Finished')
			
			startTask('Cleaning all projects')
			workspace.allProjects.forEach[
				info('''Cleaning «name»''')
				clean
			]
			endTask('Finished')
			
			startTask('Preparing all projects')
			workspace.allProjects.forEach[
				info('''Preparing «name»''')
				prepare
				if(!isValid){
					error('''project «name» is not valid''')
				}
			]	
			endTask('Finished')
	
			startTask('Building all projects')
			workspace.buildOrder.forEach[
				info('''Building «name»''')
				
				val classDir = base.toPath.resolve('bin')
				val buildpath = buildpath.map[file.toPath]
				val src = sourcePath.map[toPath]
				
				JkJavaCompiler.of.compile(new JkJavaCompileSpec => [
					outputDir = classDir
					classpath = buildpath
					addSources(src)
				])
				src.forEach[JkPathTree.of(it).refuse('**/*.java').copyTo(classDir)]
				
				build.forEach[info('''Created bundle «toString»''')]
			]
			endTask('Finished')
		} catch (Exception exception) {
			exception.printStackTrace
		} finally {
			workspace?.close
			System.exit(0) // BndPomRepository.verion(bsn) creates non-background threads?
		}
	}
	
	def static void main(String[] args) {
		JkInit.instanceOf(BndWorkspaceBuild, args).doDefault
	}
}
```

**Comment by Sandared** [comment]
By the way, I just wanted to say thanks for your work on Jerkar. I really love to write my buildscripts in Java and finally being able to use an IDE for those ;)

I got my bnd/OSGi workspace build working and even added a task to it that transpiles Xtend sources to Java.

If you ever plan to extract the logic for a plugin you can have a look at [this project](https://gitlab.com/jatoms/workspace-template/tree/master/cnf) where my build is located.

Kind regards,
Thomas

**Comment by djeang** [comment]
Great !!!
First time I see Jerkar used with Xtend :-) 
I'll try to factor out your current work in a plugin when I'll have time to. Then you may enrich the plugin to fullfill your needs (I am not an OSGI user so I can't figure out what is relevant to include in).
Note that plugins are prefered way to reuse build logic in Jerkar (mainly for self-documentation purpose) but you can also just pack build utility classes in a jar and reuse them in any build.

**Comment by Sandared** [comment]
BTW I moved the jerkar build in my project into its own [branch](https://gitlab.com/jatoms/workspace-template/tree/jerkar/cnf).

**Comment by djeang** [comment]
Hi.
Sorry, I didn't had time to work on the specific points of you mentioned. I work Jerkar on my spare time.
Anyway first release candidates for Jerkar 0.7 are out with greatly improved API and documentation, if you want to have look...

Kind regards
