### ISSUE TITLE
Flaw in JkEclipseClasspathGenerator

### ISSUE THREAD

**Issue by Chocohead** [jerkar/jeka#122]
I was wondering why every time I kept generating an Eclipse project for following (very simple) Jeka project the sources and javadoc would always fail to attach:
```java
JkJavaProject project = javaPlugin.getProject();
project.addDependencies(JkDependencySet.of()
	.andFile(JkLocator.getJekaJarPath(), JkJavaDepScopes.PROVIDED)
);
```
Having stepped through the file resolution it seems [`JkEclipseClasspathGenerator#writeClasspathEl`](https://github.com/jerkar/jeka/blob/master/dev.jeka.core/src/main/java/dev/jeka/core/api/tooling/eclipse/JkEclipseClasspathGenerator.java#L270) is the root cause of the trouble. It is trying to strip `.jar` off the end of the path's file system's `toString` rather than the path's own representation.

Think it should be as simple as
```java
String name = JkUtilsString.substringBeforeLast(file.getFileSystem().toString(), ".jar");
```
to
```java
String name = JkUtilsString.substringBeforeLast(file.toString(), ".jar");
```
Would PR the single line fix but it's far more interesting playing about with what else Jeka offers (which is a whole lot of great stuff by the way). So nice to be able to step through to problems rather than be thrown through layers of stacktrace like Gradle makes you.

On a related note, the lines below are using `-getSources` which should probably be `-sources` instead. Going by the naming Jeka itself ships with at the very least.

**Comment by djeang** [comment]
Thanks for your help @Chocohead . As Intellij is now my main IDE, Eclipse integration may have suffered somehow. Your feedback  is quite appreciated.
