### ISSUE TITLE
Task log timings are inverted

### ISSUE THREAD

**Issue by Chocohead** [jerkar/jeka#123]
In `JkLog`, `#startTask` and `#endTask` act on opposite ends of the `START_TIMES` `LinkedList`:
[`#startTask`](https://github.com/jerkar/jeka/blob/master/dev.jeka.core/src/main/java/dev/jeka/core/api/system/JkLog.java#L133) pushes the current time into the list, meaning that it is the first element. [`#endTask`](https://github.com/jerkar/jeka/blob/master/dev.jeka.core/src/main/java/dev/jeka/core/api/system/JkLog.java#L144) however polls last, which removes the final element of the list, meaning the very first time `startTask` was called. This results in sub tasks claiming to take longer than the entire project starting up does:
```
Initializing class com.chocohead.loom.LoomCommands... 
│ Instance decorated with plugin class com.chocohead.loom.JkPluginLoom[runOffline = false]
│ Fetching manifests ... 
│ │ <work>
│ └ Done in 1027 milliseconds.
│ Instance decorated with plugin class dev.jeka.core.tool.builtins.scaffold.JkPluginScaffold[]
│ Instance decorated with plugin class dev.jeka.core.tool.builtins.eclipse.JkPluginEclipse[jreContainer = null, useVarPath = true]
│ Run instance initialized with options []
└ Done in 562 milliseconds.
```

Either they'll both want to be switched to `push` and `pop` to add subtasks to the start of the list, or `addLast/offerLast` and `removeLast` so the two operations are consistent.

I'd also say it would be nice for `JkLog#endTask(String)` to expose the time taken in some way so it can be logged as part of the message rather than it having to be calculated by the caller. Potentially using `String#format` if message contains `%d`, or changing the method to take a `DoubleFunction<String>`. That being said, I haven't actually needed to use it myself yet so feel free to ignore the suggestion ;)

**Comment by djeang** [comment]
Great. I like the `%d` idea . I will introduce it in this fix.
