### ISSUE TITLE
Jeka's troubles on Windows

### ISSUE THREAD

**Issue by Chocohead** [jerkar/jeka#125]
Found this from someone else trying I project I made, apparently both the core and wrapper of Jeka have issues being run from the `jeka.bat` and `jekaw.bat` scripts.

Launching Jeka from `jeka.bat` fails to fill the classpath properly when both `LOCAL_BUILD_DIR` and `JEKA_HOME` are not set. This comes from the leading backslash:
```bat
set "COMMAND="%JAVA_CMD%" %JEKA_OPTS% -cp "%LOCAL_BUILD_DIR%%JEKA_HOME%\dev.jeka.jeka-core.jar" dev.jeka.core.tool.Main %*"
```
Java apparently silently ignores being unable to find `\dev.jeka.jeka-core.jar` causing it to fails to load with:
```
Error: Could not find or load main class dev.jeka.core.tool.Main
```
Removing the leading backlash or adding `.` before it (to get `dev.jeka.jeka-core.jar` and `.\dev.jeka.jeka-core.jar`) both fix the problem and it starts fine when the jar is present in the project root. Not sure whether either of those solutions work when either of the environment variables are present. Potentially it just needs to warn when neither are present or use `%~dp0` too like `jekaw.bat` does.

Launching the wrapper with `jekaw.bat` fails in a more nuanced way. For normal directories it works very well (besides #124), but for any directory with a space in the path it fails to launch. Trying to run `java# eclipse#files` from `D:\Jeka\Path\With space\` for example results in
```
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <"> at index 24: D:\Jeka\Path\With space" java#
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at java.nio.file.Paths.get(Paths.java:84)
        at dev.jeka.core.wrapper.Booter.main(Booter.java:34)
```
Having moved the quotes all around `jekaw.bat`, which often resulting in the space in the path being completely cut off:
```
No file found at D:\Jeka\Path\With\jeka\wrapper\jeka.properties. Please rerun 'jeka scaffold#wrap
```
I settled on this as a solution which appears to be happy no matter where it's run from
```bat
set "COMMAND="%JAVA_CMD%" %JEKA_OPTS% -cp "%LOCAL_BUILD_DIR%%~dp0jeka\wrapper\*" dev.jeka.core.wrapper.Booter "%~dp0." %*"
```

I can make a PR for both fixes if you want

**Comment by djeang** [comment]
Nice Job  ! Of course I would be pleased you make a PR.

**Comment by djeang** [comment]
I want to notice that JEKA_HOME environment variable MUST be set in order to run jeka.bat. It indicates where is installed Jeka on the running machine. So no need to work around if missing :
jeka.bat should just throw an error message if it is not the case.
