### ISSUE TITLE
Adding repos to JkPluginJava feels overly long

### ISSUE THREAD

**Issue by Chocohead** [jerkar/jeka#126]
Having needed to rely on more than Maven Central proved to be more of a nuisance than expected. Whilst adding a dependency to a `JkJavaProject` is nice and easy, adding additional repositories seems substantially more complicated.

Dependencies can be simply chained using `JkJavaProject#addDependencies` yet the only way to add additional repos to a project is to go through the `JkJavaProjectMaker` and do something like
```java
JkJavaProjectMaker project = javaPlugin.getProject().getMaker();
project.setDependencyResolver(project.getDependencyResolver().andRepos(JkRepoSet.of("https://jitpack.io/")));
```
On top of that, doing it in `JkCommands#setup` doesn't work as any changes are mysteriously replaced after the plugins are all activated. Certainly not the end of the world to do it in `JkCommands#setupAfterPluginActivations` instead, but it a weird restriction which feels unintentional. I was testing the resolution as part of running `eclipse#files` so it might be to do with that, but I can't work out why if it is.

It would be nice to have some kind of equivalent to `add/setDependencies` on `JkJavaProject` itself for adding additional or directly setting repositories, that was also happy to be used in setup. Of course I might just be missing something obvious in which case I'd happily like to know it.

**Comment by djeang** [comment]
I agree with your statement, and I'm still not happy with that and we must find a way to do it better.
Issues come from two facts :
* `JkDependencyResolver` is immutable
*  When using `JkPluginJava`, `JkJavaProject` instances are set up by java plugin which in turn use the  `JkPluginRepo` to setup repo.

For the first, I can add a `JkJavaProject#setDownloadRepos` shorthand method. I try to not overload classes with two many methods but I think this one make sense as it is a common case.

For the second, that's more a design dilemma : should we prevent java plugin to define the project download repository when this one has already been programmatically set in the setup method. If we should, this mean that user has no chance to setup the download repo through  `-repo#downloadUrl` option.

**Comment by djeang** [comment]
I have pushed new behavior for `JkPluginRepo` now it adds its repos to the project configuration instead of replacing it.
In consequence, now `project.getMaker().addDownloadRepo(JkRepo.of("https://jitpack.io/"));` in `setup`method should be fine.
What do you thing of this solution ?

**Comment by Chocohead** [comment]
That's the solution I would have suggested in `JkPluginRepo` to fix the problem, don't think there is any need for anything else more complicated. It certainly feels more natural for the download and/or publish repos to be added rather than replacing any previous repos.

As for the overload in `JkJavaProjectMaker`, it looks good enough to me. Would be nice for `JkJavaProject` itself to have a method straight to the maker's but you are certainly right that a class can have too many utility methods (especially if they are only saving you a single method call anyway).

Thanks for the quick solutions for both problems 👍

**Comment by djeang** [comment]
As a rule of thumb `JkJavaProject` holds project structure information (the what to build) while `JkJavaProjectMaker` contains information about how making  the project (tasks + infrastructure config as repositories). 
Adding shortcut methods to `JkJavaProject` would just add confusion... even if I admit that in a first stage, new users may expect to find such methods directly on `JkJavaProject`. That was the initial design. I splitted to `JkJavaProjectMaker` cause `JkJavaProject` was cluttered with too many methods.
