### ISSUE TITLE
JkScopeMapping#ALL_TO_DEFAULT doesn't really work

### ISSUE THREAD

**Issue by Chocohead** [jerkar/jeka#132]
I came across this as part of working around #103, LWJGL does resolve properly when given an explicit scope mapping. The problem is that `ALL_TO_DEFAULT` doesn't properly act like everything, and more like a scope on its own. This is noticed accidentally from #131:
```java
JkModuleDependency dependency = JkModuleDependency.of("org.lwjgl:lwjgl:3.2.2");
JkScopedDependency scoped = JkScopedDependency.of(dependency, JkJavaDepScopes.PROVIDED).withScopeMapping(JkScopeMapping.ALL_TO_DEFAULT);

JkResolveResult result = JkDependencyResolver.of(repos...).resolve(JkDependencySet.of(Collections.singleton(scoped)), JkJavaDepScopes.SCOPES_FOR_COMPILATION);
```
As `ALL_TO_DEFAULT` provides its scope name as `*` it doesn't match any of the normal `JkJavaDepScopes`. Meaning the scope mapping makes the dependency appear to be in no scopes rather than all of them as the name would suggest. This results in `#resolve` taking all scopes (which is where #131 comes in that I'd expect it to return an empty list).

More to the point however, is that it introduces `*` as a valid scope for Ivy to try resolve. Because Ivy saves caches of each scope's resolution (in `~/.jeka/cache/repo`) it will attempt to create a file called `anonymousGroup-anonymousName-*.xml` which being an invalid file name then causes it to crash completely.

I worked around this by creating the necessary scope mapping for the provided/runtime dependencies directly. For the purposes I needed this worked fine: 
```java
//Normal dependency
JkScopeMapping.of(JkJavaDepScopes.PROVIDED).to("default(*)");
//Native dependency
JkScopeMapping.of(JkJavaDepScopes.RUNTIME).to("default(*)");
```

**Comment by djeang** [comment]
I think `JkScopeMapping#ALL_TO_DEFAULT` should not be public as it leads to confusion. It will be removed.
You finally found the proper way to use scope mapping :-) 

Note that lighter notation are available as  :
```
JkScopeMapping.of("provided", "runtime").to("default(*)");
```

**Comment by Chocohead** [comment]
Strange that only LWJGL seems to require a scope mapping but I'd rather it work with one than not at all. Thanks for all the quick fixes 👍

**Comment by djeang** [comment]
Indeed, it may be due to the fact that "native" artifacts leads in a specific ivy configuration mapping.
I should write a specific test case for LWJGL when I a'll have time.
