### ISSUE TITLE
DependencySet doesn't handle duplicate dependencies

### ISSUE THREAD

**Issue by Chocohead** [jerkar/jeka#135]
When a `JkDependencySet` has multiple versions of the same dependency, it appears that the first one to be added wins regardless of the version:
```java
JkScopedDependency oldDep = JkScopedDependency.of(JkModuleDependency.of("com.google.guava:guava:21.0"), JkJavaDepScopes.PROVIDED);
JkScopedDependency newDep = JkScopedDependency.of(JkModuleDependency.of("com.google.guava:guava:28.1-jre"), JkJavaDepScopes.PROVIDED);

JkDependencyResolver resolver = JkDependencyResolver.of(JkRepo.ofMavenCentral(), JkRepo.ofMavenJCenter());
JkResolveResult result = resolver.resolve(JkDependencySet.of(Arrays.asList(newDep, oldDep)), JkJavaDepScopes.SCOPES_FOR_COMPILATION).assertNoError();
//result contains the 28.1 jar

JkResolveResult result = resolver.resolve(JkDependencySet.of(Arrays.asList(oldDep, newDep)), JkJavaDepScopes.SCOPES_FOR_COMPILATION).assertNoError();
//result contains the 21.0 jar
```
I thought there might be a work around using a version provider, but the javadoc seems correct that it only effects transitive dependencies rather than the whole set:
```java
JkResolveResult result = resolver.resolve(
	JkDependencySet.of(Arrays.asList(oldDep, newDep))
		.withVersionProvider(JkVersionProvider.of(JkModuleId.of("com.google.guava", "guava"), "28.1-jre")), 
	JkJavaDepScopes.SCOPES_FOR_COMPILATION).assertNoError();
//result still contains the 21.0 jar
```

**Comment by djeang** [comment]
I agree, dependencyProvider should also act on direct dependencies. 
I am having a look.

**Comment by djeang** [comment]
I was asking to myself ... Why do you need to declare twice the same dependency with a different version for each ?

**Comment by Chocohead** [comment]
It's not something I'd aim to do, but something that could accidentally happen: I have a few jars as dependencies which themselves have transitive dependencies. These dependencies are declared within a json file inside the jar itself rather than in the pom (so a much simpler runtime part can load them). Thus I can read that file to get the extra dependencies that are needed for compiling, but those dependencies could conflict with other ones explicitly added to the project (such as the json file needing Guava 21 whilst I add Guava 28).

If the jars properly declared transitive dependencies I'd be fine as that all seems to resolve as you'd expect picking the newest version, but they don't so I was hoping `JkDependencySet` could pick the newest version like Ivy does with actual transitive dependencies from maven.

**Comment by djeang** [comment]
Does it fill your need if I add a `JkDependencySet.withoutDuplicates` method that remove duplicate declared dependendencies with the lowest  ? 
I think removing silently duplicates may lead in confusion when such situation happen.

**Comment by Chocohead** [comment]
That sounds like a good way of handling it. I agree it might be unexpected that adding a dependency does nothing if another newer version of it is already present.

**Comment by djeang** [comment]
Brand new version of Jeka is available with great overall improvement. Have a look here https://jeka.dev/
