### ISSUE TITLE
[Question] About Throwable StackTrace

### ISSUE THREAD

**Issue by NekoCaffeine** [jerkar/jeka#138]
at [Main#main](https://github.com/jerkar/jeka/blob/e14c45154020d48eb14087e79a3dd097cd779e26/dev.jeka.core/src/main/java/dev/jeka/core/tool/Main.java#L61)
Is it possible to print a full stack trace here?
This may hide some useful information.

**Comment by djeang** [comment]
Normally, JkException is to mention user error (e.g. deleting a file that does not exist) 
Jeka should not print an intimidating stacktrace when such error happens.
However I can display stacktrace on JkException but only when verrbose mode (-LV ) is activated. 
Does it fit your need ?

**Comment by NekoCaffeine** [comment]
yep, all I need is this.

**Comment by djeang** [comment]
Brand new version of Jeka is available with great overall improvement. Have a look here https://jeka.dev/
