### ISSUE TITLE
[Question] Does jeka support multiple JkCommands implementations?

### ISSUE THREAD

**Issue by NekoCaffeine** [jerkar/jeka#144]
It seems that jeka does not seem to support multiple JkCommands implementation classes.
I hope that some of the methods that can only be run on my machine are in another JkCommands implementation class.
what should I do?

**Comment by djeang** [comment]
Yes it does. Just create another class, say `org.myorg.MyBuild2`, extending  `JkCommands` in *jeka/def* then mention the name in this class in command line as : `jeka -CC=MyBuild2 doSomething`. 
`-CC=Xxxx` is the way to specify a command class to use.

**Comment by NekoCaffeine** [comment]
I understand, thx
