### ISSUE TITLE
[Feature Request] JkJarPacker#makeFatJar Custom Filter.

### ISSUE THREAD

**Issue by NekoCaffeine** [jerkar/jeka#145]
I hope I can exclude some files from the dependencies.
Like: Function<JkDependency, PathMatcher>

**Comment by djeang** [comment]
By using `JkJarPacker#makeJar` you won't embedded any dependencies in your jar.
If you want to make a fat jar, you must use `JkJarPacker#makeFatJar` instead.
Once fat Jar is produced you can perform filter by removing element from it using something like : `JkFileTree.of(fatJar).andMatching(false, "**/filestoremove/*).zipTo(filteredFatJar)`

**Comment by NekoCaffeine** [comment]
oh, yep!
I mean the makeFatJar method.
Removing elements is not a complete solution. Because maybe I need a file from dependency A, and both B and C may have this file.
Another situation is that I need to merge the same files, such as files under META-INF/services.

**Comment by djeang** [comment]
I think that manifest files from the main jar should not be overriden by those of the dependencies. I am not sure it is actually the case. Does such a behaviour will satisfy your need ?

**Comment by Chocohead** [comment]
Duplicate files from dependences merged into a single fat jar definitely overwrite each other, I've had my project's `MANIFEST.MF` file be squished by a dependency's. Dependencies can do it to each other too, if more than one provides a service they will squish each other's declaration in the `META-INF/services` directory.

How best to handle the scenario is debatable though. On the surface it would be easiest if any dependency jar's `META-INF` (and contents) are just skipped from merging completely to avoid conflicting with the project's, but then for cases when there isn't a conflict it could be breaking a dependency that would otherwise be fine. Perhaps a general filter/`Predicate` whilst prioritising the project's files over any dependency is the simplest option so conflicts can be manually resolved if and when the arise?

**Comment by djeang** [comment]
Yes, I think that, at least, the manifest of the main jar should be preserved.
I can also add a filters to discard files,  from the resulting jar as it's already done for excluding signature files.  What do you think of ?

**Comment by NekoCaffeine** [comment]
If the filter can be customized, it's fine.
Can you add another solution by the way? Automatically generate the class-path property.
Similar to this: https://github.com/AmadeusSystems/amadeus.maho/blob/master/jeka/def/amadeus/maho/build/Build.java#L58-L92

**Comment by djeang** [comment]
> Can you add another solution by the way? Automatically generate the class-path property.
Similar to this: https://github.com/AmadeusSystems/amadeus.maho/blob/master/jeka/def/amadeus/maho/build/Build.java#L58-L92

If I understand it correctly, this is not related to Fat Jar but more to a 'distrib' packaging consisting in a folder with the main jar at the root and dependency jars located in a 'libs' sub-directory. Isn't it ?

**Comment by NekoCaffeine** [comment]
> If I understand it correctly, this is not related to Fat Jar but more to a 'distrib' packaging consisting in a folder with the main jar at the root and dependency jars located in a 'libs' sub-directory. Isn't it ?

That's it! Because the path in the class-path property must be loaded from outside the jar.

**Comment by djeang** [comment]
@NekoCaffeine Is that ok now for the fat jar generation ?

**Comment by djeang** [comment]
> That's it! Because the path in the class-path property must be loaded from outside the jar.

You can already achieve it with very few line of code : 
```
 private void makeManifest(Path classDir, Path distribDir, JkClasspath classpath) {

        // copy all deps in libs dir
        classpath.forEach(path -> JkPathFile.of(path).copyToDir(distribDir.resolve("libs")));
        
        // create Class-Path value
        StringBuilder cp = new StringBuilder();
        JkPathTree.of(distribDir).andMatching("libs/*.jar").getFiles().forEach(path -> cp.append(path + " "));

        // Create a Manifest and add it to the class dir at the proper location
        JkManifest.ofEmpty().addMainAttribute("class-path", cp.toString()).writeToStandardLocation(classDir);
    }
```

Is it fine enough ?

**Comment by NekoCaffeine** [comment]
> @NekoCaffeine Is that ok now for the fat jar generation ?

Looks good
