### ISSUE TITLE
JkManifest.IMPLEMENTATION_TITLE Spelling mistake

### ISSUE THREAD

**Issue by NekoCaffeine** [jerkar/jeka#147]
https://github.com/jerkar/jeka/blob/c0e7cc5d230d621a98f21689fa03baef8304de73/dev.jeka.core/src/main/java/dev/jeka/core/api/java/JkManifest.java#L52
`"Implementation_Title"` -> `"Implementation-Title"`

**Comment by djeang** [comment]
Indeed. Thank you.
