### ISSUE TITLE
Improve JkPathTree zip extraction

### ISSUE THREAD

**Issue by Chocohead** [jerkar/jeka#148]
The path tree API is really nice for interacting with directories and jars, although it does have one kind of annoying inconvenience when trying to extract from the tree:

When trying to replace logic such as this...
```java
try (FileSystem fs = FileSystems.newFileSystem(jar, null)) {
	Files.copy(fs.getPath("com/chocohead/Thing.class"), base, StandardCopyOption.REPLACE_EXISTING);
} catch (IOException e) {
	throw new UncheckedIOException("Error extracting class", e);
}
```
There isn't an easy option for extracting out of anything but the root of the tree. Which combined with the fact each `JkPathTree` needs closing after use to avoid leaking the zip handles results in having to do something like...
```java
try (JkPathTree parentTree = JkPathTree.ofZip(jar); JkPathTree tree = parentTree.goTo("com/chocohead/Thing.class")) {
	tree.copyTo(base, StandardCopyOption.REPLACE_EXISTING);
}
```

At least as far as I can tell. This is in contrast to adding files to the tree which is much cleaner:
```java
try (FileSystem fs = FileSystems.newFileSystem(new URI("jar:" + jar.toUri()), Collections.singletonMap("create", "true"))) {
	Path destination = fs.getPath("com/chocohead/Thing.class");

	Files.createDirectories(destination.getParent());
	Files.copy(base, destination, StandardCopyOption.REPLACE_EXISTING);
} catch (URISyntaxException e) {
	throw new IllegalStateException("Cannot convert jar to URI?", e);
} catch (IOException e) {
	throw new UncheckedIOException("Error importing class", e);
}
//All replaced with
try (JkPathTree tree = JkPathTree.ofZip(jar)) {
	tree.importFile(base, "com/chocohead/Thing.class", StandardCopyOption.REPLACE_EXISTING);
}
```
Although even that does have the little problem that if any of the parents of the destination string don't exist it will fail to copy. It would be nice if that could ensure the destination always exists in the zip with a call to `JkUtilsPath.createDirectories` before `Files#copy`.

**Comment by djeang** [comment]
Agree.
Easy for the last point.
For the first, may I introduce a new method "copySubDirTo".
What do you think of ?

**Comment by djeang** [comment]
> There isn't an easy option for extracting out of anything but the root of the tree. Which combined with the fact each JkPathTree needs closing after use to avoid leaking the zip handles results in having to do something like...
```java
try (JkPathTree parentTree = JkPathTree.ofZip(jar); JkPathTree tree = parentTree.goTo("com/chocohead/Thing.class")) {
	tree.copyTo(base, StandardCopyOption.REPLACE_EXISTING);
}
```

You don't need to do that as `goto` does not create a new zip handler so the following should be ok :
```java
try (JkPathTree parentTree = JkPathTree.ofZip(jar)) {
	parentTree.goTo("com/chocohead/Thing.class")).copyTo(base, StandardCopyOption.REPLACE_EXISTING);
}
```

**Comment by djeang** [comment]
By the way `goTo` should only accept directory as argument. I added a guard to prevent bad usage leading in unclear exceptions.

**Comment by Chocohead** [comment]
Ah, I never noticed it reused the same zip handler internally. That does make it not nearly so bad, especially if you're extracting from several different child directories. It would still be nice to have an analogous method to `importFile` for exporting/extracting individual paths though.

**Comment by djeang** [comment]
I added `JkPathTree#copyFile`.
