### ISSUE TITLE
[Question] Does jeka have offline mode?

### ISSUE THREAD

**Issue by NekoCaffeine** [jerkar/jeka#152]
I hope not to do dependency checking every time during frequent builds.

**Comment by djeang** [comment]
How did you declare your dependencies ? Normally Ivy should not do remote checking when all decencies are already in cache. Did you use wildcard  versions as xxxx:xxxxxxx:1.0.+ or snapshots  ?

**Comment by NekoCaffeine** [comment]
Yes i used the wildcard '+'

**Comment by djeang** [comment]
Ok so Ivy has to check for a potential new version anyway. You just need to replace + by the concrete Version number and ivy would not check remotely anymore I think.

**Comment by NekoCaffeine** [comment]
Maybe I should implement an offline mode myself.

**Comment by NekoCaffeine** [comment]
What happens if ivy's connection is blocked?

**Comment by djeang** [comment]
Envoyé de mon iPhone

**Comment by djeang** [comment]
If dependencies declared with '+' version is coming from local build, then you should consider using an *computed dependency* rather than a *module* one. See https://github.com/jerkar/jeka/blob/master/dev.jeka.core/src/main/doc/Reference%20Guide/1.3.%20Dependency%20management.md
