### ISSUE TITLE
Allow setting native library paths

### ISSUE THREAD

**Issue by Chocohead** [jerkar/jeka#153]
For libraries that have native components, such as LWJGL, in order to work properly at runtime they need the folder with all the native components in explicitly passing in some way. For Eclipse at least this is done as part of the `.classpath` file:
```xml
<classpathentry kind="lib" path="libs/lwjgl-2.9.0.jar" sourcepath="libs/lwjgl-2.9.0-sources.jar">
	<attributes>
		<attribute name="org.eclipse.jdt.launching.CLASSPATH_ATTR_LIBRARY_PATH_ENTRY" value="Project/libs/lwjgl-2.9.0"/>
	</attributes>
</classpathentry>
```
It would be helpful if there was a way to explicitly put this extra metadata effectively onto the dependency so the IDE project generators could attach it. This extra metadata could be less library and more project specific too, for example, setting imports as discouraged from a particular library:
```xml
<classpathentry kind="lib" path="libs/lwjgl-2.9.0.jar" sourcepath="libs/lwjgl-2.9.0-sources.jar">
	<attributes>
		<attribute name="org.eclipse.jdt.launching.CLASSPATH_ATTR_LIBRARY_PATH_ENTRY" value="Project/libs/lwjgl-2.9.0"/>
	</attributes>
	<accessrules>
		<accessrule kind="nonaccessible" pattern="never/import/this/**"/>
		<accessrule kind="discouraged" pattern="dont/import/this/**"/>
		<accessrule kind="accessible" pattern="you/can/import/this/**"/>
	</accessrules>
</classpathentry>
```
Not entirely sure what kind of equivalence IDEA has for this but I presume it has something along similar lines.

**Comment by djeang** [comment]
I am not sure we can make common feature for Intellij and Eclipse butit's not a big issue.
I think the simplest is to add Eclipse specific methods :  `JkPluginEclipse#addAttribute(String entryId, key, value)` and `JkPluginEclipse#addAccessRule(String entryId, kind, pattern)` where `entryId` stands for a string representation of a declared dependencies (module of file). With these information it's pretty straightforward to produce the enriched `.classpath` file.
What do you think about ?

**Comment by Chocohead** [comment]
Sounds perfect for what I need. Shame about IntelliJ but I suppose it does things differently to Eclipse so can't be expecting miracles from it.

**Comment by djeang** [comment]
Last commit implements the discussed design. Please can you tell me if it's fine for you ? Do you see something that it can be done better ?

**Comment by Chocohead** [comment]
Sorry for not getting back to you sooner, been super busy since Christmas.

What you've got is just like what imagined. Don't think it not working on computed dependencies should be a problem especially either, not that it'd be a bad fix if anyone does need it to in future. On a very related note it might be helpful (if it's not already possible) to be able to get the `JkDependency` that a plugin is loaded from a runtime so it can have access rules applied. Right now I'm doing:
```java
JkResolveResult resolveResult = getCommands().getRunDependencyResolver().resolve(dependencies);

for (JkDependencyNode node : resolveResult.getDependencyTree().getChildren()) {
	for (Path jar : node.getResolvedFiles()) {
		if ("jar".equals(MoreFiles.getFileExtension(jar))) {
			try (JkPathTree tree = JkPathTree.ofZip(jar)) {
				//See if the plugin class is in the jar
				if (Files.exists(tree.get(getClass().getName().replace('.', '/') + ".class"))) {
					if (node.isModuleNode()) {
						origin = JkModuleDependency.of(node.getModuleInfo().getModuleId(), JkVersion.UNSPECIFIED);
					} else {
						assert !((JkFileNodeInfo) node.getNodeInfo()).isComputed();
						origin = JkFileSystemDependency.of(node.getNodeInfo().getFiles());
					}

					break asFound; //Jump far out of this block
				}
			} catch (UncheckedIOException e) {
				throw new UncheckedIOException("Error checking dependency: " + node, e.getCause());
			}
		}
	}
}
```
Would be helpful if there was a more certain way of doing it, if there's not this will still work as a solution.

**Comment by djeang** [comment]
Hi,
Sorry, I don't understand what you are trying to do. Can you share the repo url ?

**Comment by djeang** [comment]
Dependency mechanism has been deeply reworked in last versions (0.9.10.x). I think this issue has been tackle within.
