### ISSUE TITLE
Add project-specific "organize imports" settings to eclipse project

### ISSUE THREAD

**Issue by giorgiga** [jerkar/jeka#155]
The eclipse project specifies a save action to organize imports but, as the settings for it are not shared, the actual import statements will depend on each developer's default configuration.

**Comment by djeang** [comment]
Sorry for late reply,

I am currently working on Intellij so it is not so quick for me to switch eclipse to code and test such a feature.... and I would say, why not share the settings file ? 
Anyway, I don't thing it's a big deal to implement. For example you can create a class `JkEclipseSettingManager` if you feel it up.
