### ISSUE TITLE
Unable to find dependencies

### ISSUE THREAD

**Issue by iamnk** [jerkar/jeka#158]
I am using the java-classic working example project. I run the build class on IntelliJ itself. But unable to find the location where the dependency jars are downloaded. It's also not available in the output jars

**Comment by djeang** [comment]
Hi,
You'll find them in [USER_HOME]/.jeka/cache/repo. I will add a note to the documentation.

**Comment by iamnk** [comment]
Thanks @djeang for your quick response.
But how about defining the custom path for the downloading dependencies!
And also, why we have chosen to store the dependencies in a commonplace?

**Comment by djeang** [comment]
It is stored in a common place by default to minimize download over the network, this common place acts as a cache. This is ok for most of usage.
Can you tell me, please, what you want to achieve ? May there is simple way to do it without "redirecting" download. For exemple, you can get the download result by using `javaPlugin.getProject().getMaker().fetchDependencies()`. From the result, you can easily get resolved files to copy them in the place of your choice.
