### ISSUE TITLE
Link for downloading any of 0.9.0.M10 artifacts leads to 404

### ISSUE THREAD

**Issue by Voiteh** [jerkar/jeka#163]
Hi when trying to download jeka leading from main page to maven download page, there is issue downloading any of artifacts in "Download" context menu.

![obraz](https://user-images.githubusercontent.com/38067799/93707354-d989ac80-fb2d-11ea-986f-2920db615c36.png)

Click download and select any of artifacts.
![obraz](https://user-images.githubusercontent.com/38067799/93707372-3d13da00-fb2e-11ea-92c5-9611edde6683.png)

**Comment by NekoCaffeine** [comment]
You can download through this link first: https://repo1.maven.org/maven2/dev/jeka/jeka-core/0.9.0.M10/jeka-core-0.9.0.M10-distrib.zip

**Comment by Voiteh** [comment]
Yeah I know, I browsed through maven repo ;)
