### ISSUE TITLE
Cannot add custom repositories

### ISSUE THREAD

**Issue by JozefDropco** [jerkar/jeka#174]
https://jeka.dev/docs/reference.html#Repositories this link says I can define more url for one repository unfortunately I am not able to get it working. We have internal mirror of maven central for security purposes. I am unable to link it to local mirror.

I tried 
repo.downloadName=mirrors
repo.mirrors.url=https://******/internal
repo.mirrors.url=https://******/thirdparty
repo.mirrors.url=https://******/external

I also tried on same line but without any success. Only the last one is always took into acount. What am I doing wrong?

**Comment by djeang** [comment]
Hi,

The doc says `Note that you can define several urls for a repo.[repo name].url by separating then with coma (as repo.def.url=http://my.repo1, http://my.repo2.snapshot).`

Is this working properly for you ?
