### ISSUE TITLE
JkPluginPom not working - empty dependecies generated

### ISSUE THREAD

**Issue by JozefDropco** [jerkar/jeka#175]
I tracked down the issue to JkQualifiedDependencies getDependenciesHavingQualifier. 
` List<String> list = Arrays.asList(qualifiers);
       return entries.stream()
                .filter(qDep -> list.contains(qDep))`

qDep is instance of JkDependency and list contains returns always false

**Comment by djeang** [comment]
I have fixed a no <dependencies> tag in version 0.9.10.RELEASE but i am not sure it is related to your problem.

I've also added  a working example for pom plugin at https://github.com/jerkar/working-examples/tree/master/migrate-from-maven

Do you still have the issue ? If so, can you provide your pom.xml ?
