### ISSUE TITLE
Linux file permissions not stored in zip file

### ISSUE THREAD

**Issue by amottier** [jerkar/jeka#179]
I'm building Jeka from source using Jeka wrapper version `0.9.11.RELEASE`.

After cloning the repository I can see that `dev.jeka.core/src/main/java/META-INF/bin/jeka` is executable.

After the build, `jeka` file that is packaged in `dev.jeka.jeka-core-distrib.zip` is no longer executable.

A possible solution to preserve file permissions would be to rely on [Apache Commons Compress](https://commons.apache.org/proper/commons-compress/) that allows to [set Unix permissions](https://commons.apache.org/proper/commons-compress/apidocs/org/apache/commons/compress/archivers/zip/ZipArchiveEntry.html#setUnixMode-int-) when creating an archive.

**Comment by djeang** [comment]
Indeed. 
I am looking a way to to do it without rewriting the whole `CoreBuild#distrip.zip` method. I am afraid i cannot avoid this.

**Comment by amottier** [comment]
I can confirm the fix, thanks a lot :+1:
