### ISSUE TITLE
Load dependencies dynamically in runtime

### ISSUE THREAD

**Issue by assimbly** [jerkar/jeka#195]
Question: Is it possible to load a dependency (jar file) dynamically at runtime with Jeka? (For example with the JkUrlClassLoader)

**Comment by djeang** [comment]
Indeed, you can do it using ´JkUrlClassLoader#addEntries'.

**Comment by assimbly** [comment]
OK, great. I have another question:

I tried to run it like this:

JkUrlClassLoader.ofSystem().addEntries(paths);

But then I got: "The current or system classloader is not instance of URLClassLoader but class jdk.internal.loader.ClassLoaders$AppClassLoader. It is probably due that you are currently running on JDK9."

Since JDK9 the addUrl method is protected, so cannot be used directly. I am running a Spring Boot (2.4) application on JDK11. Is this why the method is deprecated? Is there a way to still use it? I tried to load my own classloader which extenses the UrlClassLoader while adding the addUrl againa as public method, but no luck yet.

**Comment by djeang** [comment]
This method supposes that the system classloader is an URLClassloader, which is not on JDK >= 9. 
I wonder why you need to add an entry on the system class loader. 
Maybe you want to do `JkUrlClassloader.ofCurrent()`. 
This method is deprecated cause it is not a proper way (still doable) to add entry on the basic URLClassloader. The proper way is to create a class inheriting from URLClassloader overrideing `addURL` to make it public. Then you can create a new classloader upon the current one, and add urls on.

**Comment by assimbly** [comment]
Thanks for you help. I am aware of the changes on the system classloader since JDK9. I did try

JkUrlClassloader.ofCurrent()

This seems to do something, because it's changed the error message from:

"please check your classpath contains the needed Camel component jar."

to

"Caused by: org.apache.camel.ResolveEndpointFailedException: Failed to resolve endpoint: scheduler://hello?delay=10000 du
e to: Cannot auto create component: scheduler" 

Which exactly also indicates a classpath error. It's probably because it's not instantiate all classes application wide. For now I know what's possible from within Jeka. 

More in general I need to rethink my approach towards loading jar files dynamically. I already made a SO question on it:
 
https://stackoverflow.com/questions/70066951/how-to-load-jar-files-dynamically-at-runtime-in-jdk11

Thanks for a lot your help (I do enjoy using Jeka), you can close ticket as my questions are answered.

**Comment by djeang** [comment]
If you give more context or share your build class I may advise you how to do it right. Not than you can use @JkDefClasspth to add any dependency/jar in your build class for free.

**Comment by skin27** [comment]
It's an open source project, so you can check the code. It has two parts:

1. Spring boot application: https://github.com/assimbly/gateway
2. The Spring Boot applicationg contains a Camel application: https://github.com/assimbly/connector

(More Background Info Here: https://github.com/assimbly/gateway/wiki)

The applications main class is: https://github.com/assimbly/gateway/blob/master/src/main/java/org/assimbly/gateway/GatewayApp.java

The Jeka dependency resolver / Java classloader class is this file: https://github.com/assimbly/connector/blob/master/baseModule/src/main/java/org/assimbly/util/DependencyUtil.java

Feel free to check/give advice. It would be of course great if Jeka could dynamically loading dependencies (jar files from a directory or local/central repository).

**Comment by djeang** [comment]
I see clearer, you use Jeka as a lib and not as an automation tool. That's fine too.
I think you should get deeper knowledge to deal with  classloader properly. For example, i don't think it's correct to act on the system classloader, see also 'context Classloader'. 
To have a look is your current classloader and jars loaded in, you can simply do a `System.out.println(JkClassloader.ofCurrent());`

Hope it helps

**Comment by skin27** [comment]
Thanks a lot, I definitly look into to it. I use Jeka as a lib, because so I can do things programmatically within the application (a lot of things that are not possible with Maven or Gradle).

**Comment by assimbly** [comment]
Just to let you know I found a solution. Not a few lines of code, but it worked in some tests I did. I updated the StackOverflow question and implementated this in my develop branch (https://github.com/assimbly/connector/blob/develop/baseModule/src/main/java/org/assimbly/util/DependencyUtil.java)
