### ISSUE TITLE
Incremental Compilation

### ISSUE THREAD

**Issue by Hardebayho** [jerkar/jeka#200]
Does the java plugin have some sort of incremental compilation? Don't know if this is the right term, but what I'm asking is that, does the java plugin recompile every source file on invocation of build or only the ones that have changed?

If it has some sort of incremental compilation, can you please tell me how it works? Just a high level description will suffice, I just want to understand it. BTW, thanks for this awesome tool!!! 🙏

**Comment by djeang** [comment]
I never tried to perform incremental compilation with Jeka nevertheless you can use Eclipse compiler which feature incremental compile. I am interested in your feedback if you manage to. See https://github.com/jerkar/jeka/blob/master/dev.jeka.core/src/main/doc/FAQ.md#how-can-i-use-eclipse-compiler-in-jeka-

**Comment by Hardebayho** [comment]
The link you provided is a 404

**Comment by djeang** [comment]
Sorry, this one matches the last release  https://github.com/jerkar/jeka/blob/0.9.15.RELEASE/dev.jeka.core/src/main/doc/FAQ.md
